version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_database
    environment:
      - POSTGRES_USER=matheus
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=albumtracker
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - albumtracker

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - albumtracker
volumes:
  api:
  database_postgres:

networks:
  albumtracker: